# Generated by Django 3.2.3 on 2021-07-30 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_rename_answer_choice'),
    ]

    operations = [
        migrations.AddField(
            model_name='choice',
            name='text',
            field=models.CharField(default='', max_length=1000),
            preserve_default=False,
        ),
    ]
